development-ping/UNION-back

src/main/java/com/develop_ping/union/common/error/ErrorCode.java
src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/dto/request/GatheringListCommand.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringDetailInfo.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringInfo.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/domain/strategy/GatheringDateSortStrategy.java
src/main/java/com/develop_ping/union/gathering/exception/GatheringPermissionDeniedException.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/party/domain/PartyManager.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java

close #76 
- 모임 수정 API 개발
없음
없음

feat: 모임 수정 API (#76)

---

src/main/java/com/develop_ping/union/comment/domain/dto/CommentCommand.java
src/main/java/com/develop_ping/union/comment/domain/service/CommentService.java
src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
src/main/java/com/develop_ping/union/comment/presentation/CommentController.java

- todo 적어놓았음
> #82 
> 댓글 논리 삭제를 위한 TODO 작성!!
> 잊어버리지 않기 위해서 올립니다..

refactor: 댓글 논리 삭제 1단계(#82)

---

src/main/java/com/develop_ping/union/auth/domain/RefreshTokenManager.java
src/main/java/com/develop_ping/union/auth/domain/entity/RefreshToken.java
src/main/java/com/develop_ping/union/auth/infra/RefreshTokenManagerImpl.java
src/main/java/com/develop_ping/union/chat/domain/entity/Chat.java
src/main/java/com/develop_ping/union/config/WebSocketConfig.java
src/main/java/com/develop_ping/union/user/domain/BlockUserManager.java
src/main/java/com/develop_ping/union/user/domain/dto/UserInfo.java
src/main/java/com/develop_ping/union/user/domain/entity/User.java
src/main/java/com/develop_ping/union/user/domain/service/CustomUserDetailsService.java
src/main/java/com/develop_ping/union/user/domain/service/UserServiceImpl.java
src/main/java/com/develop_ping/union/user/infra/BlockUserManagerImpl.java
src/main/java/com/develop_ping/union/user/infra/BlockUserRepository.java
src/main/java/com/develop_ping/union/user/infra/UserManagerImpl.java
src/main/java/com/develop_ping/union/user/infra/UserRepository.java
src/main/java/com/develop_ping/union/user/presentation/UserController.java
src/main/java/com/develop_ping/union/user/presentation/dto/response/OtherUserResponse.java
src/main/java/com/develop_ping/union/user/presentation/dto/response/UserResponse.java
src/main/resources/data.sql

> ex) close #81 
> 유저 논리 삭제 추가
> 모임 쪽 개발 완료되면 삭제 로직을 서비스에 추가해야 함
>

Feat/user 유저 논리 삭제 추가

---

src/main/java/com/develop_ping/union/common/error/ErrorCode.java
src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/exception/OwnerCannotExitException.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/party/domain/PartyManager.java
src/main/java/com/develop_ping/union/party/exception/ParticipationNotFoundException.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
src/main/java/com/develop_ping/union/party/infra/PartyRepository.java

close #92 
- 모임 나가기 API
- 모임 주최자는 나가기를 사용할 수 없음
- 모임 삭제를 해야 됨

feat: 모임 나가기 API (#92)

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringDetailResponse.java
src/main/java/com/develop_ping/union/party/domain/PartyManager.java
src/main/java/com/develop_ping/union/party/domain/dto/PartyInfo.java
src/main/java/com/develop_ping/union/party/domain/entity/Party.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
src/main/java/com/develop_ping/union/party/infra/PartyRepository.java
src/main/java/com/develop_ping/union/user/domain/entity/User.java
src/test/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImplTest.java
src/test/java/com/develop_ping/union/party/infra/PartyRepositoryTest.java

close #91 
- 모임 삭제 버그 해결
- 연관 관계 추가
- 연관 관계 추가 후 코드 정리

bug: 모임에 가입된 유저가 있을 때 삭제가 안된던 버그 해결 (#91)

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java

close #98 
- 내가 작성한 모임글 리스트 API

feat: 내가 작성한 모임글 리스트 API (#98)

---

src/main/java/com/develop_ping/union/comment/domain/service/CommentServiceImpl.java
src/main/java/com/develop_ping/union/photo/domain/service/PhotoServiceImpl.java
src/main/java/com/develop_ping/union/post/domain/service/PostServiceImpl.java

> close #104 
> comment, post, photo의 log 메시지를 통일성 있게 변경하였습니다.
>

refactor: comment, post, photo의 log 메시지 수정(#104)

---

src/main/java/com/develop_ping/union/post/presentation/PostListController.java
src/main/java/com/develop_ping/union/reaction/presentation/ReactionController.java
src/main/java/com/develop_ping/union/reaction/presentation/dto/PostReactionResponse.java

> 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요. (이미지 첨부 가능)
>

Refactor: temp post likes

---

src/main/java/com/develop_ping/union/auth/infra/OAuthUnlinkManagerImpl.java
src/main/java/com/develop_ping/union/chat/infra/ChatManagerImpl.java
src/main/java/com/develop_ping/union/chat/infra/ChatroomManagerImpl.java
src/main/java/com/develop_ping/union/chat/presentation/WebSocketController.java
src/main/java/com/develop_ping/union/user/infra/BlockUserManagerImpl.java
src/main/java/com/develop_ping/union/user/infra/UserManagerImpl.java

> ex) close #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요. (이미지 첨부 가능)
>

fix: 트랜잭션 수정

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringListResponse.java
src/main/java/com/develop_ping/union/party/domain/PartyManager.java
src/main/java/com/develop_ping/union/party/domain/entity/Party.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
src/main/java/com/develop_ping/union/photo/domain/service/PhotoServiceImpl.java
src/main/java/com/develop_ping/union/reaction/domain/ReactionManager.java
src/main/java/com/develop_ping/union/reaction/infra/ReactionManagerImpl.java
src/main/java/com/develop_ping/union/reaction/infra/ReactionRepository.java
src/main/resources/data.sql

close #121 
모임 리스트를 불러올 때 다음의 정보들 추가
- 장소 정보 추가
- 작성자 정보 추가
- 썸네일 추가

feat: 모임 리스트 불러올 때 정보 추가 (#121)

---

src/main/java/com/develop_ping/union/chat/domain/dto/MessageInfo.java

fix: 빼먹은 로직 수정

---

src/main/java/com/develop_ping/union/chat/infra/ChatManagerImpl.java
src/main/java/com/develop_ping/union/common/error/ErrorCode.java
src/main/java/com/develop_ping/union/common/error/ErrorHandlingController.java
src/main/java/com/develop_ping/union/config/auth/WebSecurityConfig.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringInfo.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/exception/GatheringNotFoundException.java
src/main/java/com/develop_ping/union/gathering/exception/RecruitmentAlreadyCompletedException.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringResponse.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java

close #126 
- 모임 게시 상태 변경 API
- 모임 채팅 연동

feat: 모임 게시 상태 변경 API (#126)

---

src/main/java/com/develop_ping/union/chat/infra/ChatroomRepository.java

> ex) close #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요. (이미지 첨부 가능)
>

fix: 채팅방 계속 생성되는 버그 수정

---

src/main/java/com/develop_ping/union/party/domain/PartyManager.java
src/main/java/com/develop_ping/union/party/domain/entity/Party.java
src/main/java/com/develop_ping/union/party/infra/PartyManagerImpl.java
src/main/java/com/develop_ping/union/party/infra/PartyRepository.java

close #133 
- 특정 사용자가 참여한 모든 모임 리스트 불러오는 API

feat: 특정 사용자가 참여한 모든 모임 리스트 불러오는 API (#133)

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java

close #141 
- 모임에 참여한 유저 강퇴 API (#141)
- 기존의  service를 무겁게 하는 방식에서 manager를 좀 더 무겁게 하는 방식으로 변경

feat: 모임에 참여한 유저 강퇴 API (#141)

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
src/main/java/com/develop_ping/union/gathering/domain/entity/Gathering.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringRepository.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/party/presentation/PartyController.java

close #143 
- 내가 참여한 모임 목록 API

feat: 내가 참여한 모임 목록 API (#143)

---

build.gradle

close #151 
- Querydsl 환경 설정
#151 의 내용을 잘 확인하자.
`clean` > `build` > `compileJava` 이후 Q클래스 들이 잘 생성되는지 확인

chore: Querydsl 환경 설정 (#151)

---

src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java

close #154 
- 모임 좋아요 API
- 추후 성능 문제가 발생할 수 있을 거 같음
- 현재 reaction 테이블에 직접적인 insertion, deletion 작업, 이에 따른 성능 이슈가 발생할 것 같음

feat: 모임 좋아요 API (#154)

---

src/main/java/com/develop_ping/union/notification/presentation/NotificationController.java
src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForCommentRequest.java
src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForGatheringRequest.java
src/main/java/com/develop_ping/union/notification/presentation/dto/request/NotificationCreationForPostRequest.java

> 
> 알람 에러 확인을 위한 valid 추가
> 
>

fix: notification controller dto valid 추가

---

src/main/java/com/develop_ping/union/notification/domain/dto/NotificationInfo.java
src/main/java/com/develop_ping/union/notification/domain/dto/NotificationListInfo.java
src/main/java/com/develop_ping/union/notification/infra/NotificationRepositoryCustomImpl.java
src/main/java/com/develop_ping/union/notification/infra/dto/NotificationReadForService.java
src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponse.java
src/main/java/com/develop_ping/union/notification/presentation/dto/response/NotificationReadForResponseList.java
src/main/resources/data.sql

> close #162 
알림 read 중 response 형식에 해당 창작물(게시글, 댓글, 모임) id 추가
- data.sql 에 더미 데이터로 notification data insert 진행

fix: add typeid in response value

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringHotListInfo.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/infra/HotGatheringQuery.java
src/main/java/com/develop_ping/union/gathering/infra/response/GatheringWithLikes.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringHotListResponse.java
src/main/resources/data.sql

close #156 
모임 인기글 API
- 1) 좋아요 수가 높은 순
- 2) 모임 일정이 가까이 있는 순

feat: 모임 인기글 API (#156)

---

src/main/java/com/develop_ping/union/gathering/domain/GatheringManager.java
src/main/java/com/develop_ping/union/gathering/domain/GatheringSortStrategy.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringService.java
src/main/java/com/develop_ping/union/gathering/domain/service/GatheringServiceImpl.java
src/main/java/com/develop_ping/union/gathering/infra/DynamicSortStrategy.java
src/main/java/com/develop_ping/union/gathering/infra/GatheringManagerImpl.java
src/main/java/com/develop_ping/union/gathering/presentation/GatheringController.java

close #169 
- 모임 목록을 불러올 때 `나를 차단한`, `내가 차단한` 유저의 글은 불러오지 않습니다.

feat: 모임 목록 list에서 차단 유저 필터링 기능 추가 (#169)

---

compose.yaml

close #171 
- docker 내 mysql 한국어 설정

chore: docker 내에 있는 mysql 한국어 설정 (#171)

---

src/main/java/com/develop_ping/union/gathering/domain/dto/request/GatheringCommand.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringHotListInfo.java
src/main/java/com/develop_ping/union/gathering/domain/dto/response/GatheringListInfo.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/request/GatheringRequest.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringHotListResponse.java
src/main/java/com/develop_ping/union/gathering/presentation/dto/response/GatheringListResponse.java

close #173 
- 모임 생성시 썸네일 추가
- 모임 목록 응답 모임 생성 일시 추가

refactor: 모임 부분 수정 (#173)

---

src/main/resources/data.sql

> close #177
> 모임 관련 더미데이터 추가
> 유저 더미데이터 수정

chore: 모임 관련 더미데이터 추가(#177)

---

src/main/resources/data.sql

> 모임 사진 더미데이터 추가
> 추가되어있던 사진 데이터 오타 제거

chore: 더미데이터 수정
